# Nick Namer Config, available tags for Secrecy are +nick, +name
Colored Tags: false
Secrecy:
    Enabled: false
    Join: '&e+nick &ejoined the game'
    Leave: '&e+nick &eleft the game'
    Kick: '&e+nick &ewas kicked'