name: NickNamer
main: bukkit.killjoy64.NickNamer.NickNamer
version: 0.8.1
commands:
    nick:
        description: Name Commands
        usage: /nick <NickName>
    realnick:
        description: find the name of a player
        usage: /realnick <Player>
    nicknamer:
        description: Access NickNamer commands
        usage: /nicknamer <Arg1> <Arg2>...
        aliases: nn
permissions:
    nickname.nick:
        description: Permission to NickName!
        default: op 
    nickname.nick.other:
        description: permission to rename others!
        default: op
    nickname.notify:
        description: Permission to be notified of name changes!
        default: op
    nickname.help:
        description: Permission to see Nick Namer help!
        deafult: op
    nickname.realnick:
        description: Permission to see their REAL Minecraft NickName.
        default: op